---

- hosts: localhost
  remote_user: root
  gather_facts: true
  tasks:
    - name: Print Extra variables passed via Curl 
      debug:
        msg: "{{ IP }}  {{ MAC }}"
      register: Ip_Details
      
    - name: concatenate into a file
      shell: echo "{{ IP }}  {{ MAC }}" >> /tmp/INV
